[tool.poetry]
name = "inspect-ai-scorers"
version = "0.1.7"
description = ""
authors = ["abigailhaddad <abigail.haddad@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"